### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by EllieDuan** [nf-core/slamseq#19]
Hello,

Thanks for the nf-core slamseq package. I have it run well using `slamdunk all`, this run from raw reads to count files. I'd like to have DEG analysis as well, so I tried this on the nextflow pipeline, but it gives this error message. Could you please help to give some hint where might be wrong? Thank you!

Does this issue relate to #14? 

```
Error executing process > 'tcperreadpos (2_R1_001)'

Caused by:
  Process `tcperreadpos (2_R1_001)` terminated with an error exit status (1)

Command executed:

  alleyoop tcperreadpos \
      -o tcperreadpos \
      -r genome.fa \
      -s .  \
      -mq 27 \
      -l 50 \
      -t 1 \
      2_R1_001_trimmed.fq_slamdunk_mapped_filtered.bam

Command exit status:
  1

Command output:
  (empty)

Command error:
  Creating output directory: tcperreadpos
  Running alleyoop tcperreadpos for 1 files (1 threads)
  Traceback (most recent call last):
    File "/opt/conda/envs/nf-core-slamseq-1.0.0/bin/alleyoop", line 10, in <module>
      sys.exit(run())
    File "/opt/conda/envs/nf-core-slamseq-1.0.0/lib/python3.7/site-packages/slamdunk/alleyoop.py", line 559, in run
      results = Parallel(n_jobs=n, verbose=verbose)(delayed(runTcPerReadPos)(tid, args.bam[tid], referenceFile, minMQ, args.maxLength, outputDirectory, snpDirectory, vcfFile) for tid in range(0, len(args.bam)))
    File "/opt/conda/envs/nf-core-slamseq-1.0.0/lib/python3.7/site-packages/joblib/parallel.py", line 1004, in __call__
      if self.dispatch_one_batch(iterator):
    File "/opt/conda/envs/nf-core-slamseq-1.0.0/lib/python3.7/site-packages/joblib/parallel.py", line 835, in dispatch_one_batch
      self._dispatch(tasks)
    File "/opt/conda/envs/nf-core-slamseq-1.0.0/lib/python3.7/site-packages/joblib/parallel.py", line 754, in _dispatch
      job = self._backend.apply_async(batch, callback=cb)
    File "/opt/conda/envs/nf-core-slamseq-1.0.0/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 209, in apply_async
      result = ImmediateResult(func)
    File "/opt/conda/envs/nf-core-slamseq-1.0.0/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 590, in __init__
      self.results = batch()
    File "/opt/conda/envs/nf-core-slamseq-1.0.0/lib/python3.7/site-packages/joblib/parallel.py", line 256, in __call__
      for func, args, kwargs in self.items]
    File "/opt/conda/envs/nf-core-slamseq-1.0.0/lib/python3.7/site-packages/joblib/parallel.py", line 256, in <listcomp>
      for func, args, kwargs in self.items]
    File "/opt/conda/envs/nf-core-slamseq-1.0.0/lib/python3.7/site-packages/slamdunk/alleyoop.py", line 232, in runTcPerReadPos
      stats.tcPerReadPos(referenceFile, bam, minMQ, maxReadLength, outputCSV, outputPDF, inputSNP, log)
    File "/opt/conda/envs/nf-core-slamseq-1.0.0/lib/python3.7/site-packages/slamdunk/dunks/stats.py", line 627, in tcPerReadPos
      mutCounts[mismatch.readPosition] += 1
  IndexError: list index out of range

```

**Comment by EllieDuan** [comment]
I think this might be I forgot to define read length, sorry about this trouble, great pipeline by the way!

**Comment by realzhang** [comment]
> I think this might be I forgot to define read length, sorry about this trouble, great pipeline by the way!

Excuse me, but how to define read length in nextflow? Thanks!
